### ISSUE TITLE
unsuported array::media[]

### ISSUE THREAD

**Issue by odinuv** [keboola/ex-facebook-graph-api#37]
The media was posted before the most recent time that the user's account was converted to a business account from a personal account.

https://papertrailapp.com/groups/170211/events?focus=897012383187353680&selected=897012383187353680

mel by to byt asi usererror

**Comment by kacurez** [comment]
to uz je vyriesene - extraktor chybu `media was posted before..` ignoruje, bol tam jeden specificky pripad ked na tej chybe spadol uplne, to som dnes fixol v https://github.com/keboola/ex-facebook-graph-api/pull/36

**Comment by odinuv** [comment]
ah, cool :)
