### ISSUE TITLE
App error when shutting down (exit code 143)

### ISSUE THREAD

**Issue by odinuv** [keboola/ex-facebook-graph-api#46]
https://papertrailapp.com/groups/170211/events?focus=971195984367460446&selected=971195984367460446

exit code 143

**Comment by odinuv** [comment]
mozna totez jako docker-7e16f79c06a42692f72e86db2784c71a ? kde je `RETYRING request ... e":1,"message":"Please reduce the amount of data you're asking for, then retry your request"}}`

**Comment by odinuv** [comment]
dalsi vyskyt docker-c1b8b074cf97bd1ba31565a8a3a8096f

**Comment by kacurez** [comment]
z logu(pozeral som aj job v projekte) nic podozrive nevidim, dokonca ten konfig bezne nepada
Zameral som sa na hlasku z logu: `container '437900935-437900818.437900936--0-keboola-ex-facebook-ads' failed: (143)` - podla tohto to vypada ze apka dostala SIGTERM z vonku a skoncila
https://serverfault.com/questions/695849/services-remain-in-failed-state-after-stopped-with-systemctl
`it is the way that the java VM received a SIGTERM signal, send by systemd to stop the process`
143 = 128 + 15 => 15 je SIGTERM
neviem uplne co to znamena ale mam podozrenie ze k chybe mohlo dojst "o patro vyssie". Nebudem to dalej eskalovat ale este sa ktomu vratim

**Comment by odinuv** [comment]
no dneska v noci zase dvakrat - co myslis tim o patro vys?

**Comment by odinuv** [comment]
docker runnner by to terminoval jedine pri pozadavku na ukonceni jobu - potom by to ale nezaznamenal jako app error, nebo pri prekroceni pameti - potom by se to ale melo chovat uplne jinak

**Comment by kacurez** [comment]
j mas recht

**Comment by kacurez** [comment]
tak nakoniec to bolo o "patro vys" :) Instancia sa vypla, zhodilo to beziaci ex fb kontajner(SIGTERM) ale docker-runner to este stihol zachytit vyhodnotit ako app error a ukoncit job a az potom spadol, vid log instance tu:
https://papertrailapp.com/systems/kbc-us-east-1-syrup-docker-i-0ac7d94219f92db73/events?focus=971195983650234443
alebo tu:
https://papertrailapp.com/systems/kbc-us-east-1-syrup-docker-i-05e0d2eb104fa8177/events?focus=971608709555953709

**Comment by kacurez** [comment]
tu by sa to narychlo dalo fixnut tak aby apka odignorovala SIGTERM(143) a pockala si az na SIGKILL(137)

**Comment by odinuv** [comment]
dik! to je celkem bizar, ze se to zaclo takhle najednou objevovat. instance se restartuji celkem bezne

**Comment by Halama** [comment]
oni se prave restartuji pomerne malo od te doby co zmenili chovani spotu. Posledni dva dny ale nebyla kapacita v jedne AZ a restartovala se tam isntance treba 9x po sobe behem jedne noci.

**Comment by odinuv** [comment]
jo, asi je to fakt tim, dneska to udelalo pri restartu instance zase https://keboola.slack.com/archives/C09U3R1J4/p1545289089082400

**Comment by odinuv** [comment]
@kacurez nemuze to souviset s timhle https://github.com/keboola/ex-facebook-graph-api/commit/cbde129c4ffb928ebf86bf37adf733ed23555529  ?

**Comment by kacurez** [comment]
@odinuv hmm neviem, ja som myslel ze to je problem javy. Ako myslis ze by to mohlo stym suvisiet? co som tak zbezne cital tak tam velmi nevidim suvislost
```
CMD sets default command and/or parameters, which can be overwritten from command line when docker container runs.
ENTRYPOINT configures a container that will run as an executable.
```

**Comment by odinuv** [comment]
vzpomnel jsem si na tohle https://github.com/keboola/encryption-api/issues/4
