### ISSUE TITLE
Please reduce the amount of data you're asking for, then retry your request

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/ex-facebook-graph-api#55]
Tahle response udělá párkrát retry a končí jako app error

`{"error":{"code":1,"message":"Please reduce the amount of data you're asking for, then retry your request"}}`

https://connection.keboola.com/admin/utils/logs?file=2018/10/20/03/2018-10-20-03-25-54-5bca84226f2e4-exception
https://connection.keboola.com/admin/utils/logs?file=2018/10/20/03/2018-10-20-03-25-54-5bca842273ba2-log

asi není potřeba retry a mohl by to být user error?

**Comment by kacurez** [comment]
retry je tam schvalne pretoze ten potom vola request so znizenym limitom(~ response page size) a failne ako user error az ked sa mu to nepodari 3 krat po sebe s najmensim moznym limitom(1).

Problem v tomto pripade je inde - je to vlastne duplicate https://github.com/keboola/ex-facebook-graph-api/issues/46 - apka bola zostrelena cez SIGTERM (exit code 143)
