### ISSUE TITLE
No implementation of method: :take! 

### ISSUE THREAD

**Issue by kacurez** [keboola/ex-facebook-graph-api#56]
zrejme nejaky glitch ale zatial neviem preco.
unexpected error:java.lang.IllegalArgumentException: No implementation of method: :take! of protocol: #'clojure.core.async.impl.protocols\/ReadPort found for class: clojure.lang.PersistentVector

https://connection.keboola.com/admin/utils/logs?file=2018/10/31/07/2018-10-31-07-25-44-5bd94ae804cfb-exception
https://connection.keboola.com/admin/utils/logs?file=2018/10/31/07/2018-10-31-07-25-44-5bd94ae80fa73-log

**Comment by odinuv** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1541916246011500

**Comment by kacurez** [comment]
podla logov sa to deje len v jednom projekte(2104) pre facebook ads extractor
prvykrat to nastalo 19/10/2017
query 
`
{:id 3239, :type nested-query, :name Ad_insights, :query {:path ads, :fields insights.time_increment(1).date_preset(yesterday){ad_id,ad_name,clicks,unique_clicks,frequency,impressions,objective,reach,spend,inline_link_clicks, adset_id,adset_name,campaign_id,campaign_name}, :ids , :limit 50}, :api-version v3.1}
`

**Comment by kacurez** [comment]
stack trace:

```
unexpected error:java.lang.IllegalArgumentException: No implementation of method: :take! of protocol: #'clojure.core.async.impl.protocols/ReadPort found for class: clojure.lang.PersistentVector
 at clojure.core$_cache_protocol_fn.invokeStatic (core_deftype.clj:583)
    clojure.core$_cache_protocol_fn.invoke (core_deftype.clj:575)
    clojure.core.async.impl.protocols$fn__6389$G__6384__6396.invoke (protocols.clj:15)
    clojure.core.async$do_alts$fn__11200.invoke (async.clj:252)
    clojure.core.async$do_alts.invokeStatic (async.clj:244)
    clojure.core.async$do_alts.invoke (async.clj:236)
    clojure.core.async$alts_BANG__BANG_.invokeStatic (async.clj:271)
    clojure.core.async$alts_BANG__BANG_.doInvoke (async.clj:265)
    clojure.lang.RestFn.invoke (RestFn.java:410)
    keboola.facebook.extractor.output$write_rows$fn__14166.invoke (output.clj:167)
    keboola.facebook.extractor.output$write_rows.invokeStatic (output.clj:162)
    keboola.facebook.extractor.output$write_rows.invoke (output.clj:155)
    keboola.facebook.extractor.query$run_and_write.invokeStatic (query.clj:14)
    keboola.facebook.extractor.query$run_and_write.invoke (query.clj:11)
    keboola.facebook.extractor.query$run_nested_query.invokeStatic (query.clj:44)
    keboola.facebook.extractor.query$run_nested_query.invoke (query.clj:41)
    keboola.facebook.extractor.query$run_query$run_with_user_token__14255.invoke (query.clj:86)
    keboola.facebook.extractor.query$run_query$run_query__14257.invoke (query.clj:87)
    keboola.facebook.extractor.query$run_query.invokeStatic (query.clj:89)
    keboola.facebook.extractor.query$run_query.invoke (query.clj:80)
    keboola.facebook.extractor.core$run$fn__14626.invoke (core.clj:54)
    clojure.core$map$fn__5587.invoke (core.clj:2745)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.RT.seq (RT.java:528)
    clojure.core$seq__5124.invokeStatic (core.clj:137)
    clojure.core$dorun.invokeStatic (core.clj:3125)
    clojure.core$dorun.invoke (core.clj:3125)
    keboola.facebook.extractor.core$run.invokeStatic (core.clj:50)
    keboola.facebook.extractor.core$run.invoke (core.clj:45)
    keboola.facebook.extractor.core$prepare_and_run$fn__14630.invoke (core.clj:73)
    keboola.facebook.extractor.core$treat.invokeStatic (core.clj:28)
    keboola.facebook.extractor.core$treat.invoke (core.clj:26)
    keboola.facebook.extractor.core$prepare_and_run.invokeStatic (core.clj:73)
    keboola.facebook.extractor.core$prepare_and_run.invoke (core.clj:58)
    keboola.facebook.extractor.core$_main.invokeStatic (core.clj:80)
    keboola.facebook.extractor.core$_main.doInvoke (core.clj:75)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    keboola.facebook.extractor.core.main (:-1)
```

**Comment by odinuv** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1545717786006800 v jinym projektu

**Comment by odinuv** [comment]
opet 2104 https://keboola.slack.com/archives/C09U3R1J4/p1545804125007700

**Comment by kacurez** [comment]
> https://keboola.slack.com/archives/C09U3R1J4/p1545717786006800 v jinym projektu

je to stale ten isty projekt 2104

**Comment by kacurez** [comment]
![image](https://user-images.githubusercontent.com/1412120/50637736-7623a980-0f5b-11e9-89c1-e7024370d0e2.png)
Extractor identifikuje tabulky `ads` a `page` ale nakoniec zisti ze obsahuju len idcka bez data a vyhodnoti ze ich netreba tahat, nakoniec tam teda niesu ziadne "hodnotne" data. Skusim to nasimulovat

**Comment by kacurez** [comment]
hmm tak sa mi to nepodarilo nasimulovat, pri podobnom setupe mi to nikdy nespadlo, nechavam to tak, updatnem aspon dependencies, mozno sa to tym vyriesi.

**Comment by Halama** [comment]
Dnes opět https://keboola.slack.com/archives/C09U3R1J4/p1546754584000400
Zase  na projektu `2104`, co sahá historie PT tak je to vždy jen tenhle projekt.

**Comment by kacurez** [comment]
dohodol som sa s klientom(zastupeny Radimom) ze upravi query a zvysi casove okno na 3 dni, teraz tam je 1 den(cast query `date_preset(yesterday)`)

**Comment by kacurez** [comment]
dostal som token od klienta tak to zdebugujem lokalne u seba

**Comment by kacurez** [comment]
Po debugu^^ som zistil kde je problem:
Vystupne data(== co sa ukladaju do storage tabulky) su velmi riedko rozprestrene v odpovedi z api. Preto extraktor nevidel tabulku insights ktora sa nachadzala az na "konci" odpovede. Videl len prazdne tabulky "ads" a "page" ako je to ciastocne popisane v https://github.com/keboola/ex-facebook-graph-api/issues/56#issuecomment-451130348
Zatial som to hotfixol(PR https://github.com/keboola/ex-facebook-graph-api/pull/65) tym ze som zdvojnasobil buffer v ktorom sa hladaju vystupne tabulky. Do rozsiahlejsieho fixu sa nepustam kedze to zrejme bude tomu klientovi stacit(skusal som).

Kazdopadne ak sa to objavi znovu tak sa pre debug da nasimulovat nasledovne:
- vytvorit query ktora taha commenty feedu: `path=feed fields=comments{message}`
- zmensit `sample-rows-count` na minimum, napr 2

**Comment by kacurez** [comment]
tuto zatvorim, prestalo sa to objavovat.
