### ISSUE TITLE
unsuported array::outbound_clicks

### ISSUE THREAD

**Issue by kacurez** [keboola/ex-facebook-graph-api#68]
ex fb ads
failed: (2) unsuported array::outbound_clicks[{:action_type \"outbound_click\", :value \"9\"}]

**Comment by odinuv** [comment]
failed: (2) {\"error\":{\"code\":1,\"message\":\"An unknown error occurred\",\"error_subcode\":99}}\nRETYRING request with limit  50\n{\"error\":{\"code\":1,\"message\":\"An unknown error occurred\",\"error_subcode\":99}}\nRETYRING request with limit  25\n{\"error\":{\"code\":1,\"message\":\"Please reduce the amount of data you're asking for, then retry your request\"}}\nRETYRING request with limit  13\n{\"error\":{\"code\":1,\"message\":\"Please reduce the amount of data you're asking for, then retry your request\"}}\nRETYRING request with limit  7\n{\"error\":{\"code\":1,\"message\":\"An unknown error occurred\",\"error_subcode\":99}}\nRETYRING request with limit  50\nunsuported array::outbound_clicks[{:action_type \"outbound_click\", :value \"1\"}]",

**Comment by odinuv** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1557795053123100

**Comment by odinuv** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1557881031130500

**Comment by odinuv** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1557967592137300 porad stejnej projekt 5555

**Comment by odinuv** [comment]
porad projekt 5555 https://keboola.slack.com/archives/C09U3R1J4/p1558140492010300
