### ISSUE TITLE
Handle "Please reduce the amount of data you're asking for" as user error

### ISSUE THREAD

**Issue by ErikZigo** [keboola/ex-facebook-graph-api#78]
Kdyz se pokousim extractorem nacitat velke mnozstvi dat tak facebook vrati chybu `Please reduce the amount of data you're asking for, then retry your request` a extractor skonci App Errorem

`docker-d9adb20067ec41483b6fa24ae3d0b93d`

**Comment by tomasfejfar** [comment]
Should have been fixed by #80 and https://github.com/keboola/kbc-ui/pull/4060 IMHO

**Comment by ujovlado** [comment]
https://keboola.atlassian.net/browse/COM-289
