### ISSUE TITLE
Fix media posted before recoverable error

### ISSUE THREAD

**Issue by pocin** [keboola/ex-facebook-graph-api#86]
update on https://github.com/keboola/ex-facebook-graph-api/pull/36
looks like the error message changed from `Media Posted Before Business Account Conversion` to `Media posted before business account conversion` since you implemented the fix as we are getting
```
Facebook api error:{"error":{"message":"Invalid parameter","type":"OAuthException","code":100,"error_data":{"blame_field_specs":[[""]]},"error_subcode":2108006,"is_transient":false,"error_user_title":"Media posted before business account conversion","error_user_msg":"The media was posted before the most recent time that the user's account was converted to a business account from a personal account.","fbtrace_id":"A8lGX5r60lMwL4B5nKv19u9"}}
```
 in the logs

Will make a PR for case insensitive search in a minute

**Comment by pocin** [comment]
hi @kacurez soft ping. Did you have a minute to take a look? thx!

**Comment by kacurez** [comment]
@pocin yes, will have a look today.
