### ISSUE TITLE
Comments has wrong czech chars

### ISSUE THREAD

**Issue by padak** [keboola/ex-facebook-graph-api#9]
Example:
```
njak to v textu nevidm, ten kurz se kon v danm obdob vdy 1x tdn ve tvrtek (krom 29-12-2016)? Dkuji moc za info :)
```
(https://connection.keboola.com/admin/projects/2439/storage#/tables/in.c-keboola-ex-facebook-252687720.comments)

**Comment by kacurez** [comment]
bol to problem na connection a uz to je fixnute: https://github.com/keboola/connection/issues/767
